name: Release

on:
  push:
    branches:
      - master
      - next
      - beta
      - alpha

env:
  CI: true

jobs:
  release:
    name: Build, Release & Publish
    permissions:
      contents: write
      id-token: write # needed for provenance data generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Git
        run: |
          git config --global user.email semantic-release@github.com
          git config --global user.name "Semantic Release CI"

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build, Release on GitHub & Publish to NPM
        env:
          HUSKY: '0' # By default do not run HUSKY install
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: |
          npm ci
          npx nx release --yes